In [1]:
import numpy as np
import pandas as pd
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [2]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]

In [4]:
# удалим значения общей площади и жилой площади
apartment = np.delete(apartment, [0, 1])

In [8]:
# добавим к вектору долю жилой площади в квартире (тем самым сократив кол-во переменных в векторе)
apartment = np.append(apartment, share_living_space)
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [10]:
round(apartment[4], 2)

0.53

In [12]:
len(apartment)

5

In [14]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
max(t)

31

In [15]:
x = np.array([5, 2])
y = np.array([-5, -11])
display(x+y, x-y)

array([ 0, -9])

array([10, 13])

In [19]:
wife = np.array([130, 130, 130])
husb = np.array([120, 150, 90])
grandma = np.array([2, 3, 2.5])
rate = 72

exchange_grndma = rate*grandma
total_earn = (wife+husb+exchange_grndma)
display(exchange_grndma, total_earn)


array([144., 216., 180.])

array([394., 496., 400.])

In [20]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
k1 = 2
k2 = -3
k3 = 5
result = x*k1 + y*k2 + u*k3
result

array([7, 7])

In [22]:
create = np.array([3, 4, 5, 9])
sales = np.array([1, 5, 3, 6])
price_cr = 200
price_sls = 400
total = (sales * price_sls) - (sales * price_cr) - ((create-sales)*price_cr)
total

array([-200, 1200,  200,  600])

In [26]:
#вычисление длины вектора
a= np.array([4,6,1])
round(np.sqrt(np.dot(a,a)),2)

7.28

In [28]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
matrix_df = Hut_Paradise_DF.values
matrix_df[4] #вектор параметров 5 квартиры

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [30]:
matrix_df[:,3] #вектор этажей всех квартир

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [31]:
matrix_df[2,3] # этаж 3-й квартиры

10

In [33]:
len(matrix_df[:,0]) #кол-во квартир

9

In [34]:
area = matrix_df[:,1]
liv_area = matrix_df[:,-1]
nliv_area = area - liv_area
nliv_area #вектор нежилой площади

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [38]:
exchange_rate = 0.4
rent = matrix_df[:, 0]
grvn_costs = exchange_rate * rent
grvn_costs

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [40]:
demo_time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
demo_count = matrix_df[:, -2]
total_time = np.dot(demo_time, demo_count)
total_time #продолжительность просмотров в минутах во всех квартирах за 2 недели

1348

In [43]:
# попарная ортогональность - да
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
print('(u,v):',np.dot(u,v))
print('(u,w):',np.dot(u,w))
print('(v,w):',np.dot(v,w))

(u,v): 0
(u,w): 0
(v,w): 0


In [44]:
lin_comb = 2*v + (-3)*w
lin_comb

array([-3, 14,  3,  4,  2])

In [45]:
# парная ортогональность - да
print('(u,lin_comb):',np.dot(u,lin_comb))

(u,lin_comb): 0


In [47]:
# нормировка
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)
print('u_norm[3]:', round(u_norm[2], 3))
print('v_norm[4]:', round(v_norm[3], 3))
print('w_norm[1]:', round(w_norm[0], 3))

u_norm[3]: 0.289
v_norm[4]: 0.667
w_norm[1]: 0.213


In [3]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
display(np.diagonal(Inc)) #главная диагональ

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T
display(np.fliplr(Cons).diagonal()) #отобразил зеркально и взял диагональ (получилась побочная диагональ)

array([100, 200, 100])

array([100,  80,  60])

In [4]:
real_inc = 0.87*Inc
real_inc[0]

array([ 87. , 130.5,  78.3])

In [5]:
savings = real_inc - Cons
savings[2]

array([ 61.8, -26.9, -53. ])

In [6]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [14]:
A@x

array([26, 30])

In [15]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

In [18]:
C=B@A
C[0,3]

14

In [21]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x,y,z])
G = A@A.T
G #матрица Грамма для векторов x,y,z

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [30]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

display(Count_DF, Price_DF)

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [31]:
Count_array = Count_DF.values
Price_array = Price_DF.values
gross = Count_array * Price_array
display(gross, gross[1]) #вектор выручки Бориса


array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [32]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]
com = np.array(com)
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [39]:
gross_com = com*gross
gross_com

array([[ 4.  ,  1.5 ,  3.6 ,  1.2 ,  1.  ],
       [ 0.72, 10.5 ,  0.9 ,  2.5 ,  0.6 ],
       [ 4.8 ,  4.8 ,  0.  ,  1.5 ,  0.8 ],
       [ 1.44,  1.92, 15.12,  1.12,  1.  ],
       [ 3.  , 17.5 , 16.2 ,  2.5 ,  2.7 ],
       [10.  ,  3.  ,  1.8 ,  3.4 ,  3.  ],
       [ 4.84,  0.2 ,  1.8 ,  1.25,  3.4 ],
       [ 6.3 ,  0.  , 23.25,  3.1 ,  5.6 ]])

In [37]:
gross_com.sum(axis = 1) #доход салона от комиссии по каждому стилисту

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [41]:
total_for_spec = gross - gross_com
total_for_spec.sum(axis = 1) #доход каждго стилиста за вычетом комиссии салона

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [43]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])
A_inv = np.linalg.inv(A) #поиск обратной матрицы
A_inv[1,0]

0.375

In [50]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A = np.array([v1,v2,v3,v4])
A= A.T
rank = np.linalg.matrix_rank(A)
rank #ранг - кол-во линейно независимых векторов

4

In [54]:
G = A.T@A
display(G) #матрица Грамма для системы векторов
G[0,3]

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

-35

In [55]:
det_G = np.linalg.det(G)
det_G #определитель матрицы Грамма, матрица невырожденная

3716647.9999999995

In [57]:
G_inv = np.linalg.inv(G)
display(G_inv) #обратная матрице Грамма для системы векторов
round(G_inv[2,0],3)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

-0.026

In [68]:
A = np.array([[1, 2], [-3,1], [1,2], [1,-1]])
b = np.array([1,4,5,0])
G = A.T@A
G_inv = np.linalg.inv(G)
At_b = A.T@b
w = G_inv@At_b
w

array([-0.5,  1.6])

In [69]:

G

array([[12,  0],
       [ 0, 10]])

In [70]:
y= round(-29.3 -0.26*0.2+8.4*6, 3)
y

21.048

In [2]:
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [33]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [34]:
del df['Serial No.']
A = df.values


In [35]:
C = df.corr(method='pearson')
C

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.827200           0.635376  0.613498   
TOEFL Score         0.827200     1.000000           0.649799  0.644410   
University Rating   0.635376     0.649799           1.000000  0.728024   
SOP                 0.613498     0.644410           0.728024  1.000000   
LOR                 0.524679     0.541563           0.608651  0.663707   
CGPA                0.825878     0.810574           0.705254  0.712154   
Research            0.563398     0.467012           0.427047  0.408116   
Chance of Admit     0.810351     0.792228           0.690132  0.684137   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.541563  0.810574  0.467012          0.792228  
University Rating  0.608651  0.705254  0.427047          0.690132  
SOP                0.663707  0.712154  0.408116          0.684137  
LOR                1.000000  0.637469  0.372526          0.645365  
CGPA               0.637469  1.000000  0.501311          0.882413  
Research           0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.645365  0.882413  0.545871          1.000000

In [36]:
with_res = df[df.Research == 1]
without_res = df[df.Research == 0]

In [37]:
with_res.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.824170           0.614739  0.613318   
TOEFL Score         0.824170     1.000000           0.602445  0.629436   
University Rating   0.614739     0.602445           1.000000  0.723126   
SOP                 0.613318     0.629436           0.723126  1.000000   
LOR                 0.443374     0.436199           0.573881  0.591858   
CGPA                0.806720     0.784173           0.692237  0.717750   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.802439     0.787180           0.713094  0.708238   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.443374  0.806720       NaN          0.802439  
TOEFL Score        0.436199  0.784173       NaN          0.787180  
University Rating  0.573881  0.692237       NaN          0.713094  
SOP                0.591858  0.717750       NaN          0.708238  
LOR                1.000000  0.564794       NaN          0.588558  
CGPA               0.564794  1.000000       NaN          0.892489  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.588558  0.892489       NaN          1.000000

In [38]:
without_res.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.680668           0.384715  0.371424   
TOEFL Score         0.680668     1.000000           0.495748  0.476563   
University Rating   0.384715     0.495748           1.000000  0.607496   
SOP                 0.371424     0.476563           0.607496  1.000000   
LOR                 0.365864     0.470956           0.484262  0.618680   
CGPA                0.678476     0.696774           0.516427  0.547098   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.603827     0.622458           0.428580  0.470188   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.365864  0.678476       NaN          0.603827  
TOEFL Score        0.470956  0.696774       NaN          0.622458  
University Rating  0.484262  0.516427       NaN          0.428580  
SOP                0.618680  0.547098       NaN          0.470188  
LOR                1.000000  0.562517       NaN          0.542528  
CGPA               0.562517  1.000000       NaN          0.752714  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.542528  0.752714       NaN          1.000000

In [39]:
without_res.columns = ['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit']

In [27]:
y = without_res['Chance of Admit']


(array([ 3.87054848e-18, -1.23199779e-17,  7.08294732e-17, -9.93075054e-17,
        -7.42818832e-17,  3.82193830e-17,  0.00000000e+00,  1.00000000e+00]),
 array([], dtype=float64),
 7,
 array([4.84406456e+03, 5.05061286e+01, 1.73558332e+01, 9.76620906e+00,
        7.96249944e+00, 4.16095410e+00, 1.12429080e+00, 0.00000000e+00]))

In [56]:
#OLS без стандартизации
TOEFL = without_res['TOEFL Score']
CGPA = without_res['CGPA']
A= np.column_stack((np.ones(220), TOEFL, CGPA))
w = np.linalg.inv(A.T@A)@A.T@y
w

array([-1.04486443,  0.00442727,  0.14807744])

In [49]:
TOEFL_Score = 107
CGPA = 9.1
w0 = -1.045
w1 = 0.004
w2 = 0.148
A_predict = np.array([1, TOEFL_Score, CGPA])
predict = (A_predict*w).sum() #нормальный prediction
w_predict_for_SF = np.array([w0,w1,w2])
predict_for_SF = (A_predict*w_predict_for_SF).sum() #prediction по условиям задачи в SF
round(predict_for_SF, 2)

0.73

In [62]:
# OLS со стандартизацией
toefl_mean = TOEFL.mean()
sgpa_mean = CGPA.mean()
y_mean = y.mean()

toefl_cntr = TOEFL - toefl_mean
sgpa_cntr = CGPA - sgpa_mean
y_cntr = y - y_mean

toefl_c = np.linalg.norm(toefl_cntr)
sgpa_c = np.linalg.norm(sgpa_cntr)
y_c = np.linalg.norm(y_cntr)

toefl_st = toefl_cntr / toefl_c
sgpa_st = sgpa_cntr / sgpa_c
y_st = y_cntr / y_c

A = np.column_stack((toefl_st, sgpa_st))
w = np.linalg.inv(A.T@A)@A.T@y_st
w.round(2)


array([0.19, 0.62])

In [55]:
CGPA = without_res['CGPA']
CGPA

4      8.21
7      7.90
8      8.00
9      8.60
15     8.30
       ... 
487    9.14
489    8.50
491    7.81
498    8.43
499    9.04
Name: CGPA, Length: 220, dtype: float64

In [3]:
C = np.array([[1, 0.9922], [0.9922, 1]])
x_1 = np.array([1, 2, 1, 1])
x_2 = np.array([70, 130, 65, 60])
aigen = np.linalg.eig(C)
print(aigen)
x_1 = x_1-x_1.mean()
x_2 = x_2-x_2.mean()
x_1_n = x_1/np.linalg.norm(x_1)
x_2_n = x_2/np.linalg.norm(x_2)
itog = x_1_n+x_2_n
itog = itog/np.linalg.norm(itog)
print(itog.round(4)) 

(array([1.9922, 0.0078]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))
[-0.244   0.8643 -0.2881 -0.3323]
